# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - SunshaineDockerFunctionApp

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_604a9a299a614c1db72903f818f777cc }}
        password: ${{ secrets.AzureAppService_ContainerPassword_609338ebe7b0448f8a4f4e54053be35e }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_604a9a299a614c1db72903f818f777cc }}/xk3v/azurefunctionimage:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'SunshaineDockerFunctionApp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f0ae802dd12b486d89d9457b6f589b62 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_604a9a299a614c1db72903f818f777cc }}/xk3v/azurefunctionimage:${{ github.sha }}'